spring:
  datasource:
    url: jdbc:h2:mem:appdb
    driver-class-name: org.h2.Driver
    password:
    username: sa
    hikari:
      auto-commit: false
    schema: classpath:init-schema.sql
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties.hibernate.format_sql: true
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
  h2:
    console:
      enabled: true